config/routes.rb
Rails.application.routes.draw do
  get 'admin/users'
  get 'admin/make_admin'
  get 'admin/user_can_review'
  get 'admin/books'
  get 'admin/can_do'
  get 'admin/users_report'
  get 'admin/view_as_user/:view_as_user', to: 'admin#view_as_user'
  get 'admin/view_as_self', to: 'admin#view_as_self'


  resources :book_reviews

  devise_for :users

  root to: 'home#index'

  get 'books/search', to: 'books#index'

  match 'books/deactivate/:id', to: 'books#toggle_activation', via: :get

  resources :books

  resources :ratings

  resources :followers

  mount Attachinary::Engine => "/attachinary"

  namespace :me do
    resource :invite, only: [:new, :create]
    resources :messages, only: [:index, :show]
  end


end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  #before_action :set_book_review, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /book_reviews
  # GET /book_reviews.json
  def index
    @book_reviews = BookReview.all
  end

  # GET /book_reviews/1
  # GET /book_reviews/1.json
  def show
  end

  # GET /book_reviews/new
  def new
    @book_review = BookReview.new
    if params[:book_id] =~ /^\d+$/
      @book_id = params[:book_id]
    else
      # TODO: gracefully error out
      fail
    end

  end

  # GET /book_reviews/1/edit
  def edit
  end

  # POST /book_reviews
  # POST /book_reviews.json
  def create
    @book_review = BookReview.new(book_review_params)
    @book_review.user = current_user

    respond_to do |format|
      if @book_review.save
        format.html { redirect_to @book_review, notice: 'Book review was successfully created.' }
        format.js { render :show}
      else
        format.html { render :new }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
    Message.follower_message(:book_id => @book_review.book.id, :by => @book_review.user, :kind => :book_review, :kind_id => @book_review.id)
  end

  # We don't allow users to update reviews as of yet.
  # PATCH/PUT /book_reviews/1
  # PATCH/PUT /book_reviews/1.json
  # def update
  #   respond_to do |format|
  #     if @book_review.update(book_review_params)
  #       format.html { redirect_to @book_review, notice: 'Book review was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @book_review }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @book_review.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /book_reviews/1
  # DELETE /book_reviews/1.json
  def destroy
    @book_review.destroy
    respond_to do |format|
      format.html { redirect_to book_reviews_url, notice: 'Book review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_review
      @book_review = BookReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_review_params
      params.require(:book_review).permit(:content, :book_id)
    end
end

app/helpers/book_reviews_helper.rb
module BookReviewsHelper
end

app/views/book_reviews/_book_review.html.erb
<div>
  <div> Review by: <%= book_review.user.email %> </div>
  <div class="well"> <%= book_review.content %> </div>
</div>

app/views/book_reviews/_form.html.erb
<%= form_for(@book_review) do |f| %>
  <% if @book_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
      <% @book_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <%= f.hidden_field :book_id, value: @book_id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/book_reviews/edit.html.erb
<h1>Editing book_review</h1>

<%= render 'form' %>

<%= link_to 'Show', @book_review %> |
<%= link_to 'Back', book_reviews_path %>

app/views/book_reviews/index.html.erb
<h1>Listing book_reviews</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_reviews.each do |book_review| %>
      <tr>
        <td><%= book_review.content %></td>
        <td><%= book_review.user %></td>
        <td><%= book_review.book %></td>
        <td><%= link_to 'Show', book_review %></td>
        <td><%= link_to 'Edit', edit_book_review_path(book_review) %></td>
        <td><%= link_to 'Destroy', book_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book review', new_book_review_path %>

app/views/book_reviews/new.html.erb
<h1>New book_review</h1>

<%= render 'form' %>

<%= link_to 'Back', book_reviews_path %>

app/views/book_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @book_review.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @book_review.user.email %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_review.book.title %>
</p>

<%= link_to 'Edit', edit_book_review_path(@book_review) %> |

app/views/book_reviews/show.js.erb
$('#book_reviews_container').append('<div><%= escape_javascript(render(@book_review) )%></div>');
$('.new_book_review').hide();