config/routes.rb
Rails.application.routes.draw do
  get 'admin/users'
  get 'admin/make_admin'
  get 'admin/user_can_review'
  get 'admin/books'
  get 'admin/can_do'
  get 'admin/users_report'
  get 'admin/view_as_user/:view_as_user', to: 'admin#view_as_user'
  get 'admin/view_as_self', to: 'admin#view_as_self'


  resources :book_reviews

  devise_for :users

  root to: 'home#index'

  get 'books/search', to: 'books#index'

  match 'books/deactivate/:id', to: 'books#toggle_activation', via: :get

  resources :books

  resources :ratings

  resources :followers

  mount Attachinary::Engine => "/attachinary"

  namespace :me do
    resource :invite, only: [:new, :create]
    resources :messages, only: [:index, :show]
  end


end

app/controllers/invite_controller.rb
require 'transactional_mailer'

class InviteController < ApplicationController

  def create
  	tm = TransactionalMailer.new
  	tm.send_mail(params[:email], 1)
  	redirect_to "/"
  end

end

app/controllers/me/base_controller.rb
class Me::BaseController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/me/invites_controller.rb
class Me::InvitesController < Me::BaseController
  def create

    # UserMailer.invite(invite_params[:name], invite_params[:email], current_user.id).deliver!

    firstname, lastname = invite_params[:name].split
    user_attrs = {
      email: invite_params[:email],
      firstname: firstname,
      lastname: lastname
    }
    user = User.invite!(user_attrs)
    if can?(:admin, :site) && (invite_params[:can_admin] == '1')
      user.add_role :admin
    end
    redirect_to root_url, notice: "Your invitation has been sent to #{invite_params[:name]}."
  end

  def new

  end
  def invite_params
    params.require(:invite).permit(:email, :name, :can_admin)
  end
end

app/controllers/me/messages_controller.rb
class Me::MessagesController < Me::BaseController
  def index
    @messages = Message.where('user_id = ?', current_user.id)
  end
  def show
    @message = Message.find(params[:id])
  end
end

app/views/me/invites/new.html.erb
<div class="container">
  <h1> Invite a Friend! </h1>
  <%= form_for(:invite, url: me_invite_path, method: :post) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <%= f.submit 'Send!', class: 'btn'%>
      <% if can? :admin, :site %>
        <%= f.label :can_admin, 'Invite as admin!' %>
        <%= f.check_box :can_admin %>
      <% end %>
      <br>
    </div>
  <% end %>
</div>