config/routes.rb
Rails.application.routes.draw do
  get 'admin/users'
  get 'admin/make_admin'
  get 'admin/user_can_review'
  get 'admin/books'
  get 'admin/can_do'
  get 'admin/users_report'
  get 'admin/view_as_user/:view_as_user', to: 'admin#view_as_user'
  get 'admin/view_as_self', to: 'admin#view_as_self'


  resources :book_reviews

  devise_for :users

  root to: 'home#index'

  get 'books/search', to: 'books#index'

  match 'books/deactivate/:id', to: 'books#toggle_activation', via: :get

  resources :books

  resources :ratings

  resources :followers

  mount Attachinary::Engine => "/attachinary"

  namespace :me do
    resource :invite, only: [:new, :create]
    resources :messages, only: [:index, :show]
  end


end

app/models/book.rb
require 'elasticsearch/model'
class Book < ActiveRecord::Base
  include PublicActivity::Model
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  index_name = BONSAI_INDEX_NAME
  tracked owner: ->(controller, model) { controller.current_user if (!!controller && !controller.admin_user) }
  # searchable do
  #     text :author, :title, :isbn, :tags, :rating, :review
  # end
  validates :author, :title, presence: true
  has_many :reservations
  has_many :ratings
  belongs_to :user
  has_many :book_reviews
  has_many :followers
  attr_accessor :rating
  scope :active_books, -> {where(active: true)}
  scope :active_or_mine, ->(user_id) {where("active = ? OR user_id = ?", true, user_id)}

  def approved
    !approved_at.blank?
  end

  has_attachments :photos, maximum: 1

  # validates :photos, presence: true

  def self.sorted_by_rating
    Book.all.sort_by(&:rating)
  end

  def rating
    if ! @rating_val
      count = ratings.where("score != 0").count # count ratings for this book
      if count > 0
        sum_of_ratings = ratings.where("score != 0").sum("score")
        @rating_val = sum_of_ratings/count
      else
        @rating_val = 0
      end
    end
    @rating_val
  end

  def deleteable
    # a book is deleteable if it has no reviews, and no one has rated it
    # Since we create a rating with 0 for users who view a page, even if
    # that user has not rated, we need to exclude 0 ratings.
    if book_reviews.count == 0 && ( ratings.where('score != 0').count == 0 )
      true
    else
      false
    end
  end

  def followed? user
    Follower.where("user_id = ? and book_id = ?", user.id, self.id).length  > 0 ? true : false
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource
  helper_method :get_follower, :do_search, :do_sort

  include SortHelper


  def do_search query
    query.search(params[:q]).records.to_a
  end

  def do_sort query
    sort_params = search_sort_by
    if params[:column] == "rating"
      if params[:order] == "asc"
        @books = query.sorted_by_rating
      else
        @books = query.sorted_by_rating.reverse
      end
    else
      @books = query.order("#{sort_params[:column]} #{sort_params[:order]}")
    end
  end

  # GET /books
  # GET /books.json
  def index
    if current_user
      query = can?(:admin, :site) ? Book.all : Book.active_or_mine(current_user.id)
    else
      query = Book.active_books
    end
    if params[:q]
      @books = do_search query
      # not sure how to get elasticsearch to only search within the query
      # Se we have to limit it here again
      if current_user && cannot?(:admin, :site) # non admins can only view their own inactive books
        @books.reject! {|b| !b.active && b.user_id != current_user.id}
      else # guests can only view active books
        @books.reject! {|b| !b.active}
      end
    elsif params[:column]
      do_sort query
    else
      @books = query.to_a.sort {|a,b| a.rating <=> b.rating}.reverse
    end
    @user = current_user
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @book_review = BookReview.new book: @book
    @book_reviews = @book.book_reviews
    @user = current_user
    if @user
      @rating =
        if Rating.where("book_id = ? AND user_id = ?", @book.id, @user.id).empty?
          Rating.create!(user: @user, book: @book)
        else
          Rating.where("book_id = ? AND user_id = ?", @book.id, @user.id).first
        end
    end
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    if cannot? :update, @book
      redirect_to @book, notice: 'You cannot edit this book.'
    end
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    @book.user = current_user

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if can? :update, @book
        if @book.update(book_params)
          format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        else
          format.html { render :edit }
        end
      else
        format.html {redirect_to @book, notice: 'You cannot edit this book.'}
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    if can? :destroy, @book
      @book.destroy
      respond_to do |format|
        format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html {redirect_to @book, notice: 'You may not delete this book.'}
      end
    end
  end

  def toggle_activation
    @book.active = !@book.active

    # save book on first activate
    if @book.active and (not @book.approved_at)
      @book.approved_at = Time.now
    end

    @book.save
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book has been deactivated.' }
    end
  end

  def get_follower user, book
    Follower.where("user_id = ? and book_id = ?", user.id, book.id).first
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_book
    #   @book = Book.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:photos, :author, :title, :status, :isbn, :rating, :active, :approved_at)
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_review_form.html.erb
<br>
<%= form_for(@book_review, remote: true) do |f| %>
  <% if @book_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
      <% @book_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, 'Review Book' %><br>
    <%= f.text_area :content %>
  </div>

  <%= f.hidden_field :book_id, value: @book.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/_book_reviews_list.html.erb
<div>Reviews</div>
<div id='book_reviews_container'>
  <% @book_reviews.each do |review| %>
    <%= render review %>
  <% end %>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
    <div class="field">
      <%= f.label :tags %><br>
      <%= f.text_field :tags %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">

<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

</div>

app/views/books/index.html.erb
<div class="container-fluid">
<h1>Listing books</h1>

<table class='table' style="width:100%">
  <thead>
    <tr>
      <th><%= link_to "Author", books_path(:column => "author", :order => search_sort_by[:order]), :class => "author_link" %></th>
      <th><%= link_to "Title", books_path(:column => "title", :order => search_sort_by[:order]), :class => "title_link" %></th>
      <th><%= link_to "Status", books_path(:column => "status", :order => search_sort_by[:order]), :class => "status_link" %></th>
      <th><%= link_to "ISBN", books_path(:column => "isbn", :order => search_sort_by[:order]), :class => "isbn_link" %></th>
      <th><%= link_to "Rating", books_path(:column => "rating", :order => search_sort_by[:order]), :class => "rating_link" %></th>
      <th><%= link_to "Active", books_path(:column => "active", :order => search_sort_by[:active]), :class => "active_link" %></th>
      <th>Approved at</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <% if book.active %>
        <tr>
      <% else %>
        <tr class="warning">
      <% end %>
        <td id="<%= book.id %>" class="author"><%= book.author %></td>
        <td id="<%= book.id %>" class="title"><%= link_to book.title, book %></td>
        <td id="<%= book.id %>" class="status"><%= book.status %></td>
        <td id="<%= book.id %>" class="isbn"><%= book.isbn %></td>
        <td id="<%= book.id %>" class="rating"><div id="star_<%= book.id %>"></div></td>
        <td><%= book.active == true ? "Y" : "N" %></td>
        <td>
          <% if book.approved %>
            <%= book.approved_at.strftime("%m/%d/%Y") %>
          <% else %>
            not approved 
          <% end %>
        </td>
        <td>
        </td>
      </tr>
      <script>
        $('#star_<%= book.id %>').raty({
              readOnly: true,
              start: <%= book.rating %>,
              path: '/assets'
          });
      </script>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>
</div>

app/views/books/new.html.erb
<div class="container">
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<div class="container">

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book.status %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Rating:</strong>
  <div id="star"></div>

  <script>
    $(document).on('ready', function () {
      $('#star').raty({
          readOnly: true,
          start: <%= @book.rating %>,
          path: '/assets'
      })
    });
  </script>

  <% if can? :create, Rating %>
    <strong>User Rating:</strong>
    <div id="user_star"></div>
  </p>

    <script>
    $(document).on('ready', function () {
      $('#user_star').raty({
          start: <%= @rating.score %>,
          path: '/assets',
          click: function(score, evt) {
              $.ajax({
                  url: '/ratings/' + <%= @rating.id %>,
                  type: 'PATCH',
                  data: { score: score }
              });
          }
      })
    });
    </script>
  <% end %>
<p>
  <strong>Tags:</strong>
  <%= @book.tags %>
</p>

<p>
  <strong>Active:</strong>
  <%= @book.active %>
</p>

<p>
  <strong>Approved at:</strong>
  <%= @book.approved_at %>
</p>

<% if can? :update, @book %> 
  <%= link_to 'Edit', edit_book_path(@book) %> |
<% end %>
<%= link_to 'Back', books_path %>
<br>

          <% if user_signed_in? %>

              <% if @book.followed?(current_user) %>
                    <%= button_to "UnFollow", follower_path(get_follower(current_user, @book).id), method: :delete, class: "btn btn-sm btn-danger" %>
              <% else %>
                    <%= link_to "Follow", new_follower_path(book_id: @book.id), class:  "btn btn-sm btn-success" %>
              <% end %>
              <% if @book.deleteable %>
                  <%= button_to 'Destroy', @book, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
              <% end %>
              <% if can? :admin, :site%>
                <% if @book.active? %>
                      <%= link_to "Deactivate", {controller: "books", action: "toggle_activation", id: @book.id}, class: "btn btn-sm btn-danger" %>
                <% else %>
                      <%= link_to "Activate", {controller: "books", action: "toggle_activation", id: @book.id}, class: "btn btn-sm btn-success" %>
                <% end %>
              <% end %>
          <% end %>
<% if can? :create, BookReview %>
  <%= render 'book_review_form' %>
<% end %>
<%= render 'book_reviews_list' %>
</div>