config/routes.rb
Rails.application.routes.draw do
  get 'admin/users'
  get 'admin/make_admin'
  get 'admin/user_can_review'
  get 'admin/books'
  get 'admin/can_do'
  get 'admin/users_report'
  get 'admin/view_as_user/:view_as_user', to: 'admin#view_as_user'
  get 'admin/view_as_self', to: 'admin#view_as_self'


  resources :book_reviews

  devise_for :users

  root to: 'home#index'

  get 'books/search', to: 'books#index'

  match 'books/deactivate/:id', to: 'books#toggle_activation', via: :get

  resources :books

  resources :ratings

  resources :followers

  mount Attachinary::Engine => "/attachinary"

  namespace :me do
    resource :invite, only: [:new, :create]
    resources :messages, only: [:index, :show]
  end


end

app/views/layouts/_alerts.html.erb
<% if notice %>
  <div class="alert alert-dismissable alert-success">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert%>
  <div class="alert alert-dismissable alert-danger">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<!-- Static navbar-->



      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Home</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Books<span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li>
                    <a href="<%= books_url %>">Books List</a>
                  </li>
                  <li>
                    <a href="<%= new_book_url %>">Add Books</a>
                  </li>
                </ul>
              </li>

              <% if can? :admin, :site %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <a href="/admin/users">Magage Users</a>
                    </li>
                    <li>
                      <a href="/admin/users_report">Users Report</a>
                    </li>
                  </ul>
                </li>
              <% end %>

              <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Me<span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <a href=<%= new_me_invite_path %>>Invite a friend!</a>
                    </li>
                    <li>
                      <a href="/me/messages">Books you follow</a>
                    </li>
                  </ul>
                </li>
              <% end %>
              <% if @admin_user %>
                <li>
                  <a href=/admin/view_as_self>Back to admin</a>
                </li>
              <% end %>

            </ul>
            <ul class="nav navbar-nav navbar-right">

              <li style="padding-top:15px; padding-right:10px">
                  <%= form_tag books_path, :method => :get do %>
                    <%= text_field_tag :q, params[:q], class: "search_input" %>
                    <%= submit_tag "Search", :name => nil, class: "search_button" %>
                  <% end %>
                </li>

              <% if user_signed_in? %>
                <li style="font-weight: bold; padding-top:15px"><%= current_user.email %></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
              <% else %>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> </li>
                <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">	
  <title>RailsBookCheckout</title>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= cloudinary_js_config %>
</head>
<body>

<%= render :partial => 'layouts/header' %>

<%= render :partial => 'layouts/alerts' %>


  <%= yield %>


</body>
</html>